apiVersion: v1
kind: Pod
metadata:
  name: workerpod
  labels:
    app: worker
spec:
  containers:
  - name: workercontainer
    image: vasylk/logviewer-worker:1.0.0
    ports:
    - containerPort: 17654

apiVersion: v1
kind: Service
metadata:
  name: workerservice
spec:
  ports:
    - port: 80
      targetPort: 17654
  selector:
    app: worker
  type: NodePort
